#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    site-for-contrib-d11-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^site-for-contrib-d11\.ddev\.site$`)
      
      service: "site-for-contrib-d11-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "site-for-contrib-d11-redirectHttps"
    site-for-contrib-d11-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^site-for-contrib-d11\.ddev\.site$`)
      
      service: "site-for-contrib-d11-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "site-for-contrib-d11-redirectHttps"
    site-for-contrib-d11-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^site-for-contrib-d11\.ddev\.site$`)
      
      service: "site-for-contrib-d11-xhgui-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "site-for-contrib-d11-redirectHttps"
    
    
    
    site-for-contrib-d11-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^site-for-contrib-d11\.ddev\.site$`)
      
      service: "site-for-contrib-d11-web-80"
      ruleSyntax: v3
      
      tls: true
      
    site-for-contrib-d11-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^site-for-contrib-d11\.ddev\.site$`)
      
      service: "site-for-contrib-d11-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    
    site-for-contrib-d11-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^site-for-contrib-d11\.ddev\.site$`)
      
      service: "site-for-contrib-d11-xhgui-80"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    site-for-contrib-d11-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    site-for-contrib-d11-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-site-for-contrib-d11-web:80
        
    site-for-contrib-d11-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-site-for-contrib-d11-web:8025
        
    
    
    site-for-contrib-d11-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-site-for-contrib-d11-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/site-for-contrib-d11.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/site-for-contrib-d11.key